services:
  - type: web
    name: splitwise-api
    env: node
    buildCommand: npm install && npx prisma generate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://vedant-mittal.github.io,http://localhost:3000 